def myfunc(parametr: int):
  print(parametr)
myfunc("Hello world")


def make_upper_case(s):
    upperCase = ""
    Uppercasedict = {
    "a" : "A",
    "b" : "B",
    "c" : "C",
    "d" : "D",
    "e" : "E",
    "f" : "F",
    "g" : "G",
    "h" : "H",
    "i" : "I",
    "j" : "J",
    "h" : "H",
    "i" : "I",
    "j" : "J",
    "k" : "K",
    "l" : "L",
    "m" : "M",
    "n" : "N",
    "o" : "O",
    "p" : "P",
    "q" : "Q",
    "r" : "R",
    "s" : "S",
    "t" : "T",
    "u" : "U",
    "v" : "V",
    "w" : "W",
    "x" : "X",
    "y" : "Y",
    "z" : "Z",
    " " : " ",
    "A" : "A",
    "B" : "B",
    "C" : "C",
    "D" : "D",
    "E" : "E",
    "F" : "F",
    "G" : "G",
    "H" : "H",
    "I" : "I",
    "J" : "J",
    "K" : "K",
    "L" : "L",
    "M" : "M",
    "N" : "N",
    "O" : "O",
    "P" : "P",
    "Q" : "Q",
    "R" : "R",
    "S" : "S",
    "T" : "T",
    "U" : "U",
    "V" : "V",
    "W" : "W",
    "X" : "X",
    "Y" : "Y",
    "Z" : "Z",
    "1" : "1",
    "2" : "2",
    "3" : "3",
    "4" : "4",
    "5" : "5",
    "6" : "6",
    "7" : "7",
    "8" : "8",
    "9" : "9",
    "0" : "0",
    "!" : "!",
    "," : ",",
    "." : ".",
    }
    list(s)
    for i in (s):
        upperCase = upperCase + Uppercasedict[i]
    return upperCase
